### ISSUE TITLE
AuthBoundary/LoginModal not working

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/app-platform#195]
For an issue I am working on in the user-profile-app, I am trying to let the user login again when the session has been terminated after a password update. To do so, I am trying to use the same approach as I have found in the the app-platform code:
https://github.com/dhis2/app-platform/blob/6137de798336fa76b0e8a56eb97f451693ff8b36/shell/adapter/src/AuthBoundary/LoginModal.js#L17-L44
But since this wasn't working for my own app and my logic was virtually identical, I decided to check the app-platform playground and found that this wasn't working either: https://runtime.dhis2.nu/playground/

I'm not 100% sure what is going wrong, but it's impossible to get a valid session with that login modal.

**Comment by amcgee** [comment]
@HendrikThePendric Can you expand on « it’s impossible to get a valid login session with that login modal » ?

I’m not sure I understand... are you trying to re-authenticate an expired session or start a new one?

The way the login modal is implemented now is kind of a hack because the Core doesn’t yet (support) token authentication or even provide an api login endpoint with valid return types.  Once we have those we can/will capture 401 failed requests and offer to re-auth the session within the platform itself - basically what I think you’re trying to do in the app.  (Blatant conscription effort) Want to help implement that here instead so it can be used everywhere?

**Comment by HendrikThePendric** [comment]
After consulting @amcgee on Slack, it turns out this was a configuration issue on my side. Closing this issue.
