### ISSUE TITLE
Show a friendly error if `yarn` isn't installed.

### ISSUE THREAD

**Issue by awgaan** [dhis2/app-platform#28]
We should fallback on 'npm' if yarn isn't installed.

## Expected Behavior
```sh
$ npx @dhis2/cli-app-scripts init myapp

Importing d2.config.js defaults 
No package.json found, creating one... 
Creating package scripts... 
Installing @dhis2/cli-app-scripts... 
Installing @dhis2/app-runtime... 
warning " > @dhis2/app-runtime@1.5.1" has unmet peer dependency "prop-types@^15.7.2".
 warning " > @dhis2/app-runtime@1.5.1" has unmet peer dependency "react@^16.8.6".
warning " > @dhis2/app-runtime@1.5.1" has unmet peer dependency "react-dom@^16.8.6".
 Creating entrypoint src/App.js 
 
SUCCESS! 
Run cd myapp && npm start to launch your new DHIS2 application 
```

## Current Behavior
```sh
$ npx @dhis2/cli-app-scripts init myapp

Importing d2.config.js defaults 
No package.json found, creating one... 
Creating package scripts... 
Installing @dhis2/cli-app-scripts... 
/bin/sh: yarn: command not found
 d2-app-scripts init <name>

Setup an app

Options:
  --cwd       working directory to use (defaults to cwd)
  --version   Show version number                                      [boolean]
  --config    Path to JSON config file
  --force     Overwrite existing files and configurations
                                                      [boolean] [default: false]
  --lib       Create a library                        [boolean] [default: false]
  -h, --help  Show help    
```

## Steps to Reproduce
1. Remove yarn binary from path
2. npx @dhis2/cli-app-scripts init myapp

**Comment by amcgee** [comment]
Thanks again @awgaan!

I actually think we want to require `yarn` here because we do require it other places in the tool.  For example in the `start` and `build` scripts we current rely on `yarn.lock` as well as yarn's plug-n-play feature to ensure fast and consistent builds of the shell - we would have to also include a duplicated `package-lock.json` to support `npm`, and that would significantly degrade shell bootstrapping performance as well.

That being said, I think it does make a lot of sense to show a nicer error message if `yarn` isn't installed.  I'll use this issue to track that request!
