### ISSUE TITLE
Stating the the dependencies of the app-platform explicitely

### ISSUE THREAD

**Issue by paschalidi** [dhis2/app-platform#354]
Hey 👋  

I am opening this after I finished reading the https://platform.dhis2.nu/.

As someone who has little to no clue about this package I would like to know if this Application Platform is based on react-scripts or not. For me this was not clear. 

This might seem irrelevant but as someone who has used cra before the user would be able to estimate  if this package comes with the limitations and advantages of cra or not. 

We might wanna write a sentence or two where we explain this bit. In some places it is implicitly said but I cant be sure.

**Comment by amcgee** [comment]
Hi @paschalidi - I think it's a good point that we could clarify the parallel with CRA and particularly mention that it's very easy to migrate from a CRA app to a DHIS2 Platform app (our platform is actually LESS restrictive than CRA, although it similarly restricts configurability in a few cases in deference to standardization)

However, we shouldn't specify `react-scripts` as the base for the App Platform, because that is an implementation detail of the platform which should not be exposed to the application developer.  The platform might move to `next.js` or a custom WebPack build in the future, but there shouldn't be any changes for an application built using the platform.

As such I'm going to close this issue, however if you see places where we can highlight the compatibility with CRA or want to add a how-to guide showing how to migrate a CRA app to a DHIS2 Platform app that would be great - feel free to open a PR with those changes!!

**Comment by paschalidi** [comment]
Hey @amcgee. Yeah that makes sense. 
When we move the tracker app to the Application Platform I will be keeping notes so that I can then write a migration guide. 

In relevance with CRA compatibility I wanted to ask, where do we stand regarding service workers? 
I am thinking this might be something that we would like to have (?) can you maybe elaborate a little bit on our approach regarding service workers? I know CRA is very limited towards that specific topic.
