### ISSUE TITLE
Adding a i18n dedicated section on the documentation

### ISSUE THREAD

**Issue by paschalidi** [dhis2/app-platform#355]
👋 hello! 

As someone who is completely new to the project it is challenging to fully grasp how the Application Platform supports i18n. 

It is quite clear that this happens on the runtime time by looking at the [architecture](https://platform.dhis2.nu/#/architecture). However we might want to have a dedicated section where we explain to the fellow user in steps how they can have their application translated. 

Let me know if this makes sense and I would be happy to work on writing down how the process takes place.

**Comment by amcgee** [comment]
Hi @paschalidi - Adding an i18n section would be great, I think it would be quite helpful.  I don't think we should spend too much effort extensively documenting the existing system, since we will be upgrading it soon, but definitely the extraction of i18n strings to `.pot` files and how to use the generated `.json` files in the existing system would be great in the meantime!

**Comment by paschalidi** [comment]
>  I don't think we should spend too much effort extensively documenting the existing system

Yes that makes sense. You are right, I was also thinking we could write a section on how this can be used and not so much on documenting the existing system. 

Do you know if the api of will change after we upgrade the system? I mean are there gonna be breaking changing on the way that the package is being used? I am just curious to know.

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/LIBS-20
