### ISSUE TITLE
Expand test command

### ISSUE THREAD

**Issue by ismay** [dhis2/app-platform#380]
@Mohammer5 were talking on slack about our current types of tests and how to standardize on them. We were talking about these different types of tests:

* jest unit tests
* jest cucumber tests (for feature tests that don't need to be run in the browser)
* cypress cucumber tests

Currently we have commands for running jest unit tests and cypress cucumber tests. And @Mohammer5 is working on adding something to run jest cucumber tests. These are a lot of different test types, and it'd be nice to:

* have simple top-level commands to run these types of tests
* standardize on the organisation of these types of tests (see also https://github.com/dhis2/ui/issues/45)

I've already seen a lot of different ways of organising jest unit tests for example. I would prefer us to enforce a single, consistent approach (so either a `__tests__` folder, or colocated `.test.js` files). We could then throw an error on tests that are not organised according to our recommendations.

Same goes for the jest cucumber and cypress tests. I think it'd help devs a lot if the organisation of the tests and the commands to run them are consistent across codebases.

**Comment by amcgee** [comment]
Very onboard with this, would love to consolidate our testing practices (jest/cypress/etc) into one place, and the `d2 app scripts test` command seems the right place.

We should be a little bit cautious about being overly prescriptive since this will also be used by developers outside our team, but having sane and consistent defaults makes a ton of sense.  The way I envision it would allow an escape hatch for some customization, but the default should be what we use across all of our repos and we should never use the escape hatch ourselves (except perhaps to prototype new testing practices which we'd then incorporate into the core workflow)

So in short 🎉 👍

**Comment by Mohammer5** [comment]
I think we already agreed on not using jest cucumber. The other issues are still relevant and being discussed already

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/LIBS-18
