### ISSUE TITLE
app-shell approach and best practices

### ISSUE THREAD

**Issue by aucampia** [dhis2/app-platform#96]
I'm not sure what is going on with app-shell is a good idea. It is very difficult to customize what is happening and there is basically some ghost application which does not really exist on any registry but seems like it should. Can you explain the rationale for this and maybe cite precedent for this approach? It seems like the same thing can be achieved in a way where it would be more standard and given the current status of documentation of the project if everything works in a non-intuitive way it will just make adoption more difficult and hamper development efforts.

**Comment by amcgee** [comment]
(continuing from dhis2/notes#69)
What version of `@dhis2/cli-app-scripts` are you using currently?  There have been several improvements to the platform and app-shell lately, so I would recommend upgrading and running `yarn start --force` to get the latest shell.

In general, the app-shell approach is described [in this post and video](https://dhis2.nu/2019/07/what-is-this-app-platform/).  We intentionally limit customizability to enforce best practices and ensure that DHIS2 apps behave consistently.  One design goal is, eventually, to support routing *between applications* within a single top-level web app, which will allow for a lot of powerful features such as persistent caching, data sharing, etc.

There is a fair amount of precedent for this approach, and it has proven successful in several domains.
- The most direct comparison is to `create-react-app` which intentionally hides the configuration of development toolchains and some runtime behavior (polyfills, for instance).  We are building a platform for a narrower set of use-cases (not for generic web application development), so we have a narrower set of customizations available.
- Another two precedents are Angular and Rails, which are both "locked" frameworks that restrict the scope of application development and provide consistent, un-ejectable scaffolding
- React itself is also an example of encapsulation - each component is self-contained and standalone, without needing to know anything (with few exceptions) about its parent tree
- Finally, there have been several examples of larger organizations doing exactly what we're doing here (we even borrowed the term "app shell" from them) to facilitate faster, more consistent development of applications (namely [trulia](https://www.trulia.com/blog/tech/islands-and-the-application-shell/) and [Google's PWA recommendations](https://developers.google.com/web/fundamentals/architecture/app-shell))

We do progressively expose new configuration options as the use cases arise, but we are intentionally conservative in this.  **As such, can you share the use case you are trying to serve here?**

As you noticed there is an (intentionally undocumented) `--shell` argument for the `start` command, it is intended for local platform development purposes rather than for use in building an application.

**Comment by amcgee** [comment]
@aucampia just checking in here, did you have any questions about the platform?  How are you using it or how would you like to use it?

**Comment by amcgee** [comment]
@aucampia I'm closing this issue, please re-open it or reach out to me directly if you want to discuss the impetus and architecture of the platform tools.
